### ISSUE TITLE
baseUrl variable is not generated if relative path is specified on the path or operation level in OAS file

### ISSUE THREAD

**Issue by armen-ch** [apideck-libraries/portman#408]
According to https://swagger.io/docs/specification/api-host-and-base-path/ "Relative URLs" if relative path is specified on the path level or operation level and if the definition hosted at http://localhost:3001/openapi.yaml and specifies url: /v2, the url is resolved to http://localhost:3001/v2.
So based on this my expectation is if we specify --baseUrl= http://localhost:3001 parameter for Portman and have relative path on non-global level then it should be resolved to http://localhost:3001/v2 and Portman will generate something like:
```
         "request": {
            "name": "my request",
            "url": {
              "path": [
                "v2",
                "endpoint"
              ],
              "host": [
                "{{baseUrl}}"
              ],
       . . .
       }
```
But it generates:

![portman-test-rel-url](https://user-images.githubusercontent.com/70989770/191313787-8fef89ea-630f-4cc6-b42d-ca80b222daf3.png)

My OAS example is:

```
openapi: 3.0.1
info:
  title: 'Test api'
  version: 1.0.0
servers:
  - url: https://api.{environment}.test.com
    variables:
      environment:
        default: prod  # Production server
        enum:
          - prod      # Production server
          - dev       # Development server
paths:
  '/products':
    get:
      tags:
        - Lookup products
      servers:
        - url: /v2
      summary: 'Search for a product'
      description: 'Search for a product'
      parameters:
        - name: pattern
          in: query
          schema:
            type: string
            example: Item1
          required: true
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: string
        400:
          description: not ok
          content:
            application/json:
              schema:
                type: string
```

I'm not using any config file and running with command line params:
`portman --local .\test-api.yaml --output test-portman-out.json  --baseUrl=http://localhost:3001 --runNewman false`

Also I expect that url globally defined in OAS will be overridden with the one provided as --baseUrl parameter. But actually Portman generates both in as global variables. The first is the one provided in --baseUrl parameter and the second one is the one specified in OAS.

![portma-test-vars](https://user-images.githubusercontent.com/70989770/191315504-9a5450da-6a76-404d-962f-a666b9d6ce29.png)

**Comment by thim81** [comment]
hi @armen-ch, We have a [PR](https://github.com/apideck-libraries/portman/pull/449) in the making to fix this behaviour.

**Comment by thim81** [comment]
hi @armen-ch 
🎊 We just released Portman 1.21.0, which includes the fix that solves this issue.

**Comment by armen-ch** [comment]
Hello @thim81. thank you for fixing and letting know. Now I see it generates baseUrl without duplicating it. But the problem with the relative path defined in operation level which is mentioned in this ticket still exists. According to the OAS 3 documentation "Relative URLs" section: 

> " The URLs in the servers array can be relative, such as /v2. In this case, the URL is resolved against the server that hosts the given OpenAPI definition.  . . . For example, if the definition hosted at http://localhost:3001/openapi.yaml specifies url: /v2, the url is resolved to http://localhost:3001/v2."  

See  https://swagger.io/docs/specification/api-host-and-base-path/#relative-urls
Base on the statement I expect that if we have the following in oas yaml:

```
 . . .
  '/products':
    get:
      servers:
        - url: /v2
 . . .
```
it should be resolved to
 ```
      . . .
            },
            "url": {
              "path": [
                "v2",
                "products"
              ],
              "host": [
                "{{baseUrl}}"
              ],
   . . .
```
but currently it's resolved to:
```
   . . .
            },
            "url": {
              "path": [
                "v2",
                "products"
              ],
    . . .
```
so the  "host": [ "{{baseUrl}}"], is not generated into postman file.

For an example and the configuration configuration used also see the description if this ticket. Pleas let me know if you think we need to create separate ticket for this.
